name: Generate files

on: 
  push: 
    branches: [main]
  schedule:
    - cron: '0 7 */3 * *'

jobs: 
  generate: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
      - name: Generate blocked-names.txt
        run: deno run --allow-net --allow-write --allow-read generate.ts
      - name: Upload blocked-names.txt
        uses: actions/upload-artifact@v3
        with:
          path: blocked-names.txt
          retention-days: 4
